const fs = require("fs");
const path = require("path");

function run() {
  const inputPath = path.join(__dirname, "../data/categories.json");
  const outputPath = path.join(__dirname, "../src/lib/categoriesMap.ts");

  console.log(`Reading categories from: ${inputPath}`);
  if (!fs.existsSync(inputPath)) {
    console.error(`Error: File not found at ${inputPath}`);
    process.exit(1);
  }

  const fileContent = fs.readFileSync(inputPath, "utf8");
  const parsedData = JSON.parse(fileContent);

  // Extract the inner JSON string if it is formatted inside a "content" wrapper
  let rawText = "";
  if (parsedData.content && Array.isArray(parsedData.content) && parsedData.content[0]) {
    rawText = parsedData.content[0].text;
  } else {
    rawText = fileContent;
  }

  const innerData = JSON.parse(rawText);
  const categoriesList = innerData.categories || [];

  const map = {};

  function traverse(categories, parentPath = "") {
    for (const cat of categories) {
      const currentPath = parentPath ? `${parentPath} > ${cat.name}` : cat.name;

      let slug = "";
      if (cat.url && typeof cat.url === "string" && cat.url.trim().length > 0) {
        // Extract the last non-empty part of the URL
        const parts = cat.url.trim().replace(/\/+$/, "").split("/");
        slug = parts[parts.length - 1];
      }

      // Fallback if slug extraction fails or no URL
      if (!slug) {
        slug = cat.name
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "_")
          .replace(/^_+|_+$/g, "");
      }

      // Store in map
      map[slug] = currentPath;

      if (cat.children && Array.isArray(cat.children)) {
        traverse(cat.children, currentPath);
      }
    }
  }

  traverse(categoriesList);

  const keysCount = Object.keys(map).length;
  console.log(`Generated flat categories map with ${keysCount} entries.`);

  const fileHeader = `/**
 * CATEGORIES_MAP
 * This file is automatically generated from data/categories.json.
 * It flattens the 500+ nested categories into a slug-to-path lookup table
 * for token-efficient local category matching.
 */

export const CATEGORIES_MAP: Record<string, string> = `;

  const fileFooter = `;\n`;

  const tsContent = `${fileHeader}${JSON.stringify(map, null, 2)}${fileFooter}`;

  // Ensure target folder exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, tsContent, "utf8");
  console.log(`Successfully compiled categories map to: ${outputPath}`);
}

run();
